export const data = [
  {
    "product_name": "Widget A",
    "category": "Electronics",
    "brand": "ABC",
    "supplier": "XYZ Company",
    "cost_price": 10.50,
    "retail_price": 19.99,
    "quantity": 50,
    "maximum_stock": 100
  },
  {
    "product_name": "Widget B",
    "category": "Home Decor",
    "brand": "DEF",
    "supplier": "PQR Inc.",
    "cost_price": 8.75,
    "retail_price": 14.99,
    "quantity": 25,
    "maximum_stock": 50
  },
  {
    "product_name": "Widget C",
    "category": "Clothing",
    "brand": "GHI",
    "supplier": "LMN Corporation",
    "cost_price": 12.35,
    "retail_price": 29.99,
    "quantity": 10,
    "maximum_stock": 20
  },
  {
    "product_name": "Widget D",
    "category": "Beauty",
    "brand": "JKL",
    "supplier": "UVW Ltd.",
    "cost_price": 5.25,
    "retail_price": 9.99,
    "quantity": 100,
    "maximum_stock": 200
  },
  {
    "product_name": "Widget E",
    "category": "Sports",
    "brand": "MNO",
    "supplier": "RST Co.",
    "cost_price": 18.50,
    "retail_price": 39.99,
    "quantity": 75,
    "maximum_stock": 150
  }
  ];
  
  // 50 US states array
  export const states = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
  ];
  